### ISSUE TITLE
"ROS Way" to kill goal or the whole Coverage Server?

### ISSUE THREAD

**Issue by slowrunner** [iRobotEducation/create3_examples#12]
I have been either leaving the coverage server in the foreground of one terminal window and killing it with cntl-c, or with the PID if running in the background.

Is there a more ROS-way such as sending a kill "goal"?

How do I abort the explore goal?

**Comment by justinIRBT** [comment]
If you have a handle to the Coverage Server in a node, you can look at:
https://github.com/iRobotEducation/create3_examples/blob/galactic/create3_coverage/src/behaviors/dock-behavior.cpp
as an example for how to manage an action client programmatically.  Specifically, to cancel a goal, it calls:
`m_dock_action_client->async_cancel_goal(m_dock_goal_handle);`
