### ISSUE TITLE
FeatureRequest: Coverage Server should log specific goal accepted

### ISSUE THREAD

**Issue by slowrunner** [iRobotEducation/create3_examples#14]
Currently the Coverage Server logs "Accepting goal request" when passed a proper explore goal, and continues to log actions while performing the explore goal.

The Coverage Server does not log anything for either the /dock or /undock goals.  It at least should log accepting these goals (WIBNI the Coverage Server logged what goal was accepted), and success or failure.

UPDATE: This issue asks that the "Accepting goal request" log the specific goal:

"Accepting goal request {explore | dock | undock | wall_follow}"

and log the same completion for dock, undock, wall_follow as is logged for explore:

[INFO] [1635860215.373907229] [create3_coverage]: Coverage action terminated

**Comment by alsora** [comment]
The dock and undock actions commanded by the coverage server are implementation details.
I think it's better to just print that a behavior is starting, as you described in https://github.com/iRobotEducation/create3_examples/issues/11

**Comment by slowrunner** [comment]
no problem with that - loving anything you all can get to.  I'm just having fun playing with you all's code.

**Comment by slowrunner** [comment]
Changed the title to reflect [comment ](https://github.com/iRobotEducation/create3_examples/issues/14#issuecomment-957635963)
to "log goals" instead of "log actions".

Issue https://github.com/iRobotEducation/create3_examples/issues/11 addresses that the explore goal has told the sim to do something and the bot can be seen moving, but nothing will be visible in the coverage server output until an individual  coverage server behavior (of the explore action) completes.

This issue asks that the "Accepting goal request" log the specific goal:

 "Accepting goal request {explore | dock | undock | wall_follow} 

and log the same completion for dock, undock, wall_follow as is logged for explore:
```
[INFO] [1635860215.373907229] [create3_coverage]: Coverage action terminated
```

**Comment by slowrunner** [comment]
I see my confusion now - the /undock and /dock goals (and wall follow) are not going to the coverage server at all  - they are subscribed to by the bot/sim - so the Coverage server will not display "Accepting goal" for them.   

Sorry.
