### ISSUE TITLE
The passed action is invalid

### ISSUE THREAD

**Issue by switchdoclabs** [iRobotEducation/create3_examples#30]
Hi,

I have installed and verified the ROS2 installation and the ability to talk to the Create3 Robot.

I type "ros2 action list -t" and I get the actions for the Create 3 robot.

When I try to execute the action /dock I get "the passed action type is invalid"

create3@create3-desktop:~$ ros2 action send_goal /dock irobot_create_msgs/action/DockServo "{}"
The passed action type is invalid
create3@create3-desktop:~$ ros2 action list -t
/audio_note_sequence [irobot_create_msgs/action/AudioNoteSequence]
/dock [irobot_create_msgs/action/DockServo]
/drive_arc [irobot_create_msgs/action/DriveArc]
/drive_distance [irobot_create_msgs/action/DriveDistance]
/led_animation [irobot_create_msgs/action/LedAnimation]
/navigate_to_position [irobot_create_msgs/action/NavigateToPosition]
/rotate_angle [irobot_create_msgs/action/RotateAngle]
/undock [irobot_create_msgs/action/Undock]
/wall_follow [irobot_create_msgs/action/WallFollow]
create3@create3-desktop:~$ 

What am I doing wrong?

John

**Comment by alsora** [comment]
Hi, I'm closing this ticket since it's not related to the create 3 examples.
I see that you also opened a question in the Create 3 forum https://github.com/iRobotEducation/create3_docs/discussions/178 and you received the correct answer there
