### ISSUE TITLE
Create `jazzy` branch

### ISSUE THREAD

**Issue by civerachb-cpr** [iRobotEducation/create3_examples#57]
Can you please create a `jazzy` branch for this repo? I have some changes [here](https://github.com/civerachb-cpr/create3_examples/tree/jazzy) I'd like to merge for an eventual Jazzy release of this package in support of the Turtlebot 4.

Thanks!

**Comment by justinIRBT** [comment]
I made a jazzy branch without any relevant code changes (just small doc updates replacing humble with jazzy).  I confirmed it compiles, although it has some deprecation warnings. https://github.com/iRobotEducation/create3_examples/tree/jazzy
