### ISSUE TITLE
Solve Dependency on irobot_create_msgs?

### ISSUE THREAD

**Issue by slowrunner** [iRobotEducation/create3_examples#7]
The README explains there is a dependency, but I don't know where to put irobot_create_msgs and how to build it?

Posted detailed question at https://robotics.stackexchange.com/questions/22807/getting-a-head-start-with-irobot-create3-ros2

**Comment by slowrunner** [comment]
Is this the correct solution? 
```
mkdir -p create3_examples_ws/src
cd create3_examples_ws/src
git clone https://github.com/iRobotEducation/create3_examples.git
git clone https://github.com/iRobotEducation/irobot_create_msgs.git   <--- seems to allow the build to proceed.
cd ..
colcon build
source install/local_setup.sh
```

**Comment by alsora** [comment]
The `irobot_create_msgs` dependency is a standard ROS 2 package, so there are no requirements on where to place it and how to build it (as long as the packages that depend on it, e.g. the create 3 examples, can find it). 

The two most common options are:
- clone the package in the same workspace as the examples and build everything together.
- clone the messages package in its own workspace, build it with `colcon build` and then source the setup script of this workspace before building the create 3 examples package in another workspace.

**Comment by slowrunner** [comment]
Thank you.  I'm only with ROS for a few months now creating very basic ROS2 nodes for my GoPiGo3 robot from scratch.  Eager to learn about the Create3 ROS2 nodes created by folks that already understand ROS2.
